var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                 o                              ",
   "                                                 yy                             ",
   "                                          yy                                    ",
   "                                   o   o                                        ",
   "                                  yyyyyyy                                       ",
   "                                                                            xx  ",
   "  xx                         o                                               x  ",
   "  x                         yyyy                                             x  ",
   "  x                                                        y  y  y         o x  ",
   "  x                   yyyy                            y                      x  ",
   "  x  @       o                                                               x  ",
   "  xxxxxxxx  xxx   xxxxxxxxxxxxx   xxxxxxx   xxxxxxx                  xxxxxxxxx  ",
   "         x!!x x!!!x           x   x     x!!!x     x!!!!!!!!!!!!!!!!!!x          ",
   "         x!!x x!!!x           x!!!x     x!!!x     x!!!!!!!!!!!!!!!!!!x          ",
   "         xxxx xxxxx           x!!!x     x!!!x     x!!!!!!!!!!!!!!!!!!x          ",
   "                              xxxxx     xxxxx     xxxxxxxxxxxxxxxxxxxx          ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                p                        ",
   "                                                                                  xxxx                   ",
   "                                                                                xxxvvxxx                 ",
   "                                                                                  x  x                   ",
   "                                                             o       o                                   ",
   "                                                         x   x   x   x   x                               ",
   "                                                         x!!!x!!!x!!!x!!!x                               ",
   "                                                     xx  x!!!x!!!x!!!x!!!x                               ",
   "                                                         x!!!x!!!x!!!x!!!x                               ",
   "                                              o          xxxxxxxxxxxxxxxxx                               ",
   "                                             xxx                                    o                    ",
   "                                       o     x                                     xxx                   ",
   "                                      xx     x                                                           ",
   "                                    xxxx   !!x                                xx                         ",
   "                                  xxxxxx   xxx               s   s   s   s                               ",
   "          s                     xxxxxxxxwwwxx              o   o   o   o                                 ",
   "                              xxxxxxxxxxwwwxx            x x x x x x x x x x                             ",
   "        xxxxx               xxxxxxxxxxxxwwwxx                                                          o ",
   "        xxxxx             xxxxxxxxxxxxxxwwwxx         x                        x                         ",
   "        xxxxx           xxxxxxxxxxxxxxxxwwwxx         x!!!!!!!!!!!!!!!!!!!!!!!!x          xx             ",
   "  @     xxxxx    o    xxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxx sssssssssssssssss       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                             ",
   "                                xxx                                                                          ",
   "                                xvx                                                                          ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                o                                        o                                                   ",
   "              xxxxx                                     xx                                                   ",
   "              x                  o                                                                           ",
   "             xx                  x            xxxxxx                                                         ",
   "              x                                              xx                                              ",
   "              x           x              x              xx                                                   ",
   "             xx           x!!!!!!!!!!!!!!x           o                                                       ",
   "              x           x!!!!!!!!!!!!!!x          xx                                                       ",
   "              x           xxxxxxxxxxxxxxxx                                                                   ",
   "             xx                                           xx                                              xxx",
   "              x                                                                                             x",
   "             ox                                                 o                                           x",
   "  xxx        xx                                                xx            sssssssssssssssss             ox",
   "  x x         x             xxxx                         xx                  xxxxxxxxxxxxxxxxx          xxxxx",
   "  x           x        xxxxxxvvxxxxx               o                         xxvvvxxvvvxxvvvxx             xx",
   "  x          xx      xx            xx              xx                        xxvvvxxvvvxxvvvxx             xx",
   "  x           x     xx              xx                                       xx   xx   xx   xx          xxxxx",
   "  x           x     x                          xx                        xx                                xx",
   "  x          xx     xo                         xx                        xx                                xx",
   "  x           x     xx                         xx!!!!!!!!!!!!!!!!!!!!!!!!xx                             xxxxx",
   "  x           x      xx             xx         xx!!!!!!!!!!!!!!!!!!!!!!!!xx                                xx",
   "  x          xx        xxxxxx!!xxxxx         q xx!!!!!!!!!!!!!!!!!!!!!!!!xx                                xx",
   "  x   @      xx             xxxx         sss   xxxxxxxxxxxxxxxxxxxxxxxxxxxx                             xxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                             ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             x     x     x      x      x               x           x   xxxxxxxxx   xx      x     x            ",
   "              x   x    x   x    x      x               x           x       x       x x     x     x            ",
   "               x x    x     x   x      x               x           x       x       x  x    x     x            ",
   "                x    x       x  x      x               x     x     x       x       x   x   x     x            ",
   "                x     x     x    x    x                 x   x x   x        x       x    x  x     x            ",
   "                x      x   x      x  x                   x x   x x         x       x     x x                  ",
   "                x        x         xx                     x     x      xxxxxxxxx   x      xx     x            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "    @                                                                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
